### ISSUE TITLE
big screen my subscriptions issue design

### ISSUE THREAD

**Issue by alan345** [alan345/nacho#108]
![image](https://user-images.githubusercontent.com/15246526/44886112-53197e00-ac79-11e8-844e-3c2bcb9a12a1.png)

**Comment by alan345** [comment]
@sanjay-goel please check on your big screen. thanks

![image](https://user-images.githubusercontent.com/15246526/44929128-b6a1bb00-ad0e-11e8-9fb9-9bc27dc290f4.png)

**Comment by sanjay-goel** [comment]
it works!
