### ISSUE TITLE
Fine-tune 'Acting as user' feature for admins

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#119]
In Users list, have a button that says 'Act as user'.

Then, a bar is shown at the top that shows: 'Acting as {xxxxxxx}' in red font.

In the 'Acting as user' bar, have a button that says 'Return to admin mode'.

In Acting As User mode, the entire experience should be the same as the user; when the 'Return to admin mode' is clicked, the entire experience should be an Admin's user experience.

**Comment by alan345** [comment]
@sanjay-goel Now, all data you see when you spoof account is related to user account spoofed.
/ ! \ some actions cannot be done on behalf of user: eg: Create payment card. so button is disabled:
![image](https://user-images.githubusercontent.com/15246526/45378090-5eda3e00-b5b1-11e8-964a-6e1134d10063.png)

**Comment by sanjay-goel** [comment]
The 'acting as xzy' bar should appear throughout the site, and Admin should be able to navigate the whole site as the user, and also be able to perform functions like subscribe as the user.

**Comment by alan345** [comment]
What other information you want to spoof apart from my-account?
Spoofing the whole site duplicate routes: More routes you have less security you have.

**Comment by alan345** [comment]
Today, we decide to do this feature if customer service will request to see homepage, category page and product page as a USER.
Close for now.
