### ISSUE TITLE
Fine tune My Account > Subscriptions page

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#12]
1) In the product table, remove the first row that shows the logo
2) Link the Product name to the product page
3) Change title 'Subscriptions' to 'Current Subscriptions'.

4) After the table that shows current subscriptions, add title 'Prior Subscriptions', and add a table with following columns:
- Product --> linked to product page
- Order Date
- Cancellation Date
- button: 'Resubscribe' --> linked to product page

5) For Admins, have a delete button for each Prior Subscription.... when we do a lot of testing, we will subscribe and cancel many times and it will accumulate too many cancelled subscriptions

**Comment by alan345** [comment]
image removed.
Link done.
Current Subscriptions title changed
https://github.com/alan345/nacho/commit/b92ff7e5c3c8d568487882225763e6a70a5a80b0

**Comment by alan345** [comment]
@sanjay-goel this table is not responsive. We either hide columns in mobile or do not use the <Table> element

![image](https://user-images.githubusercontent.com/15246526/42904160-f78704fc-8a88-11e8-95f5-b2087bc67343.png)

**Comment by sanjay-goel** [comment]
It would be good to have it responsive...

**Comment by alan345** [comment]
done
![image](https://user-images.githubusercontent.com/15246526/42911513-27434612-8aa0-11e8-9566-03a66b54f45c.png)
