### ISSUE TITLE
Subscriptions that are 'Ending Soon' should be treated as Subscribed

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#121]
At the moment, Ending Soon products appear on home page and product page as unsubscribed.

**Comment by alan345** [comment]
getActiveSubscriptions() {

status_in: ['ACTIVE_TRIAL', 'ACTIVE_OFF_CYCLE', 'ACTIVE_REGULAR', 'ACTIVE_UNTIL_END_BILLING']
