### ISSUE TITLE
If user has used credit card before, don't show it on Review Order page

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#122]
even if he currently has no subscriptions.
So, the condition is not whether the user has any subscriptions in his account, but whether he has used the credit card in the past.

**Comment by alan345** [comment]
I don't have this information "but whether he has used the credit card in the past." This information is handled by Stripe.
The only information I have in our database is "does user has subscriptions in NachoNacho".

That being said, as it will not be possible to delete a subscription in the future we have:
`he has used the credit card in the past` === `he has subscriptions (prior or current)`
