### ISSUE TITLE
Fix Coming Soon page for ipad browser width

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#123]
<img width="884" alt="screen shot 2018-09-06 at 4 00 40 pm" src="https://user-images.githubusercontent.com/20733069/45189629-d04f7080-b1ee-11e8-8603-89908a393fd6.png">

**Comment by alan345** [comment]
@sanjay-goel let me know if it works
![image](https://user-images.githubusercontent.com/15246526/45229510-d55a0180-b27a-11e8-9d07-a77ea22d5a84.png)

**Comment by alan345** [comment]
solved
