### ISSUE TITLE
UX issues on Summary Invoice Page

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#131]
1) On Summary Invoice Page, clicking anywhere on an Invoice Card should take you to the Individual Invoice Page

2) URL for Individual Invoice Page should be https://www.nachonacho.com/invoice/cjm13dd7g0k5i08489zlxj9ah    instead of https://www.nachonacho.com/order/cjm13dd7g0k5i08489zlxj9ah

**Comment by alan345** [comment]
it's done.
