### ISSUE TITLE
SEO - Image sizes

### ISSUE THREAD

**Issue by alan345** [alan345/nacho#132]
For category images mostly. The size in pixels is ok. the Weight in Kb is too big (quality of image), lets say max 200Kb.
here, they say, Max 100kb. https://www.techrepublic.com/blog/web-designer/tips-for-optimizing-your-web-images/ 
![image](https://user-images.githubusercontent.com/15246526/45560021-da79fc00-b7f8-11e8-9e6f-05dcb56a169a.png)

**Comment by sanjay-goel** [comment]
duplicate
