### ISSUE TITLE
Log in /Sign up buttons

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#143]
When there is no Sign up button, it is not obvious to a new user how to Sign up.

Desktop:  bring back both Log in and Sign up buttons

Mobile: Instead of Log In button, show Avatar, and in the Avatar menu, show Sign up and Log in
Once user Signs up or logs in, the Avatar menu switches to My Account and Log out

**Comment by alan345** [comment]
I rollback with what we had.

mobile
![image](https://user-images.githubusercontent.com/15246526/45849441-c5b0d300-bce6-11e8-9854-221368c1efaa.png)

desktop
![image](https://user-images.githubusercontent.com/15246526/45849444-d06b6800-bce6-11e8-82a8-f026b6bd0df9.png)

**Comment by sanjay-goel** [comment]
On mobile: Sign Up ----> Sign up

On Desktop, maybe change the color of Sign up to pink

**Comment by alan345** [comment]
ok
