### ISSUE TITLE
Don't show 'Wrong format' error while typing in email

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#144]
When signing up, as soon as I type 5 characters, it starts saying 'Wrong format.'.   It gives the impression that the user has done something wrong, which is not the case.  Don't show that error message until user has finished typing email and password and hit Return or OK.

**Comment by alan345** [comment]
done https://github.com/alan345/nacho/commit/f34ab775022ba96a9fc93c55d6822d5209e6063a
