### ISSUE TITLE
Fix sort order of My Subscriptions

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#149]
Current subscriptions: sort by descending order of Start Date (currently it is not)

Ending soon: sort by descending order of Cancel Date

Prior subscriptions: sort by descending order of End Date

**Comment by alan345** [comment]
it was already the case for Current subscriptions:
![image](https://user-images.githubusercontent.com/15246526/46113501-86c9c400-c1a3-11e8-8dc7-f4b38baf9c42.png)


as a summary:
![image](https://user-images.githubusercontent.com/15246526/46113513-9ea14800-c1a3-11e8-9a0b-c07243a1ae72.png)
https://github.com/alan345/nacho/blob/3162c6e6cee0664a95d6226a456415d45377197f/react/src/components/user/single/UserDrawer.js#L160-L181
