### ISSUE TITLE
On Checkout Page, show ‘New Account Level savings’

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#15]
Near the top, at the moment it shows ‘Your current account level savings are x’
Below that, add another line:
‘Your new account level saving will be y’

Y = % discount after the user has subscribed to that product

**Comment by alan345** [comment]
solved with new calculation:
https://github.com/alan345/nacho/commit/a12f2ef0a7bbc0632af7e7ffca9fcb841cc4ea40
