### ISSUE TITLE
Make email sender NachoNacho instead of NachoNacho.com

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#151]

**Comment by alan345** [comment]
Why? I think adding the `.com` in the sender is a good reminder for the the user.

amazon is keeping the .com:
![image](https://user-images.githubusercontent.com/15246526/45912325-544f4e00-bdd4-11e8-9ce3-31c56d205d19.png)

**Comment by alan345** [comment]
done
`from: 'NachoNacho <do_not_reply@nachonacho.com>',`
