### ISSUE TITLE
Email validation UX

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#152]
![screen shot 2018-09-21 at 6 46 16 pm](https://user-images.githubusercontent.com/20733069/45911931-adb47e80-bdce-11e8-8725-22bbc75ffc98.png)

When I click on email validation link in my email, I'm currently taken to this page.

Instead of that, take me to the home page, with a message 'Your email is now validated. Start shopping!' as a popup.

**Comment by alan345** [comment]
![image](https://user-images.githubusercontent.com/15246526/46099298-45252300-c17b-11e8-968e-0b45a6bccbc3.png)

**Comment by alan345** [comment]
text has been changed
`${user.firstName}, your email is now validated. Start shopping!`
