### ISSUE TITLE
fine-tune Seller signup page for URL_Parameter mode

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#154]
<img width="1318" alt="screen shot 2018-09-25 at 3 47 06 pm" src="https://user-images.githubusercontent.com/20733069/46047535-4e11e800-c0da-11e8-987e-9376c0babe19.png">

Remove texts:
1) {Product name} account setup
2) By signing up, you agree.......

**Comment by alan345** [comment]
done
![image](https://user-images.githubusercontent.com/15246526/46049293-67b72d80-c0e2-11e8-88a2-9c9b361fb5c1.png)
