### ISSUE TITLE
Write title 'Invoice' on top of invoice pages - both single invoice and batch invoice

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#155]
I was on the invoice page, then got distracted and went somewhere else. When I came back, I wasn't sure what I was looking at.

<img width="1128" alt="screen shot 2018-09-25 at 4 42 49 pm" src="https://user-images.githubusercontent.com/20733069/46049326-8d443700-c0e2-11e8-955e-1f26c5a1b83e.png">
<img width="1128" alt="screen shot 2018-09-25 at 4 46 46 pm" src="https://user-images.githubusercontent.com/20733069/46049333-9b925300-c0e2-11e8-9b08-4013403c91f6.png">

**Comment by alan345** [comment]
done
![image](https://user-images.githubusercontent.com/15246526/46049712-c41b4c80-c0e4-11e8-830a-36294f6427ff.png)
