### ISSUE TITLE
When signing up, on sign up page, Enter should be = OK

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#156]

**Comment by alan345** [comment]
Signup In sellers fields?

**Comment by sanjay-goel** [comment]
I meant sign up to NN account

**Comment by alan345** [comment]
the enter key is working for me in NN

**Comment by sanjay-goel** [comment]
After I enter password, if I press enter once, nothing happens. If I press enter again, it accepts it and goes to home page.

**Comment by alan345** [comment]
ok. it should be solved
