### ISSUE TITLE
Sign up links for Sellers - where to send user from Thank You page

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#17]
Hulu: https://signup.hulu.com/account

Spotify: https://www.spotify.com/us/signup/

Pandora: https://www.pandora.com/account/register

Codecademy: https://www.codecademy.com/subscriptions/proSixMonthV1/checkout

HBO Now: https://order.hbonow.com/

NYTimes: https://myaccount.nytimes.com/get-started/auth?OC=20000138860

Microsoft Office: https://signup.live.com/signup?wa=wsignin1.0&rpsnv=13&rver=6.7.6643.0&wp=SAPI&wreply=https%3a%2f%2fwww.microsoft.com%2fen-us%2fstore%2fbuy%3froute%3dcheckout&id=74335&claims=%7b%22compact%22%3a%7b%22name%22%3a%7b%22essential%22%3atrue%7d%7d%7d&contextid=43BEE17440621C73&bk=1527897251&uiflavor=web&uaid=b1218fe8ef5b4d8dab9233398b8f740f&mkt=EN-US&lc=1033&lic=1

Netflix: https://www.netflix.com/signup/regform

**Comment by alan345** [comment]
Each link will be added on the seller account. (no hard-coding):
![image](https://user-images.githubusercontent.com/15246526/43097959-8cc0b5e4-8e72-11e8-80a1-da120d65a862.png)
