### ISSUE TITLE
Change copy of bundle discount on 'Review your order' page

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#182]
Current:
Your current bundle discount is 24.6%
Your new bundle discount will be 25.0%

New:
When you subscribe to this product, your bundle discount will increase from 24.6% to 25.0%.

**Comment by alan345** [comment]
![image](https://user-images.githubusercontent.com/15246526/46923271-6898fc00-cfca-11e8-8373-3ce3ccfc515c.png)
