### ISSUE TITLE
Switch from NachoNacho.com to NachoNacho wherever possible

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#185]
Unless the '.com' is needed for URL purposes, switch from NachoNacho.com to NachoNacho.

![image](https://user-images.githubusercontent.com/20733069/46926422-8e7fca00-cfe5-11e8-848a-89a822c6240a.png)

**Comment by alan345** [comment]
done https://github.com/alan345/nacho/commit/62d89c8a6aab59e28fba0d27dfe4c5f3b65c9122
