### ISSUE TITLE
When search gives no results

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#192]
After the text 'No products.....'
add button:
'Continue shopping' and link it to home page

![image](https://user-images.githubusercontent.com/20733069/46989905-df5df400-d0b3-11e8-8469-a9553864272d.png)

**Comment by alan345** [comment]
![image](https://user-images.githubusercontent.com/15246526/47030682-06074380-d123-11e8-9037-b904a314aa6b.png)
