### ISSUE TITLE
Minimize API documentation

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#197]
Remove everything except signupDate and trialEndDate from POST.
Remove all other Optional fields from definitions in introduction.

**Comment by alan345** [comment]
fields removed: 
    "buyerLanguage": "fr",
    "buyerGender": "male",
    "buyerLocation": "New York"
    "buyerDateOfBirth": "2010-10-12T00:00:00.000Z",

**Comment by sanjay-goel** [comment]
Let's also remove

buyerLoginOnSellerSite: 
buyerLoginOnSellerSiteType:

We can introduce it later...

**Comment by alan345** [comment]
Previous api doc: https://documenter.getpostman.com/view/1855326/RWgtSwXT
actual: http://bit.ly/NachoNacho_API_Documentation
