### ISSUE TITLE
Launching Batch moves products from Ending Soon to Current Subscriptions

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#199]

**Comment by alan345** [comment]
it iw working fine with me:

![image](https://user-images.githubusercontent.com/15246526/47029264-fe926b00-d11f-11e8-9e65-fb31cb426546.png)
then: 
![image](https://user-images.githubusercontent.com/15246526/47029371-3d282580-d120-11e8-843c-f42f2971c07f.png)
then:
![image](https://user-images.githubusercontent.com/15246526/47029386-47e2ba80-d120-11e8-9b36-3c61c0adac27.png)

**Comment by sanjay-goel** [comment]
Ok, I see.   If I have a product in Ending Soon today (Oct 16), and I run a Batch on Nov 1, it moves the product from Ending Soon to Prior Subscriptions, because the system is now operating as if today's date is Nov 1.  So that's fine.
