### ISSUE TITLE
Prior subscriptions dates should be prior to current month

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#207]
<img width="1100" alt="screen shot 2018-10-23 at 9 38 56 am" src="https://user-images.githubusercontent.com/20733069/47376502-9c011800-d6a7-11e8-8cdf-6dad13d21ff0.png">

**Comment by alan345** [comment]
we hardcoded it
![image](https://user-images.githubusercontent.com/15246526/47384535-5ef35080-d6bc-11e8-9b71-dbe5be099760.png)

**Comment by sanjay-goel** [comment]
Ok, those dates were old dates, before the hardcoding was done.
