### ISSUE TITLE
add down/up arrow next to user name on top right hand corner

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#219]
example:

<img width="134" alt="screen shot 2018-10-25 at 10 59 03 am" src="https://user-images.githubusercontent.com/20733069/47520509-3ba7dd00-d845-11e8-8a4d-7c86704db53f.png">
<img width="265" alt="screen shot 2018-10-25 at 10 59 13 am" src="https://user-images.githubusercontent.com/20733069/47520510-3ba7dd00-d845-11e8-94e4-fc236c5c74ed.png">

**Comment by alan345** [comment]
done
not a bug fan thought
![image](https://user-images.githubusercontent.com/15246526/47752291-49989c00-dc51-11e8-8f05-35036b157791.png)
