### ISSUE TITLE
Fix ComingSoon website (www.nachonacho.com)

### ISSUE THREAD

**Issue by alan345** [alan345/nacho#22]

**Comment by alan345** [comment]
@sanjay-goel I think it looks more professional when title is not moving between slides.
E.g slide 3=> slide 4, tilte is not moving. 

I suggest to make it on the same position for every slides. What do you think?

http://nachonacho.com/

**Comment by sanjay-goel** [comment]
I agree... it looks nice when the title doesn't move.
But we will probably need to change the color of the text of the title, depending on the image background.  OR, maybe add a transparency behind the text, so it works in all background colors.

**Comment by alan345** [comment]
All image were set to 5seconds
