### ISSUE TITLE
UX for profile image

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#220]
When there is no image, change copy from 'Select Image' to 'Upload profile photo'

If there is an image, change copy from 'Select Image' to 'Change profile photo', and change copy from 'Remove' to 'Delete profile photo'

**Comment by sanjay-goel** [comment]
Also, remove 'By link'... it doesn't mean anything to a user.

**Comment by alan345** [comment]
`Upload profile photo` and `Change profile photo` are the same button. I just delete `Change profile photo` button.
https://github.com/alan345/nacho/commit/0850f58e02d4ed075e5095fae98b1156883ad065
