### ISSUE TITLE
editing product page

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#221]
For both by Admin and by Seller:

1) Either remove the 'By link' button, or change the copy to explain what it is.
2) Change 'Remove' to 'Delete image'
3) Change 'Upload Image' to 'Upload image'

<img width="932" alt="screen shot 2018-10-30 at 11 52 46 am" src="https://user-images.githubusercontent.com/20733069/47742707-768d8480-dc3a-11e8-85b3-70de5cdeac92.png">

**Comment by alan345** [comment]
By link means you get an image by his url link. 
Used for the affiliated image.

**Comment by sanjay-goel** [comment]
Maybe remove it from Seller's product editing UI.  Keep it for Admin.

On Tue, Oct 30, 2018 at 1:38 PM Alan <notifications@github.com> wrote:

> By link means you get an image by his url link.
> Used for the affiliated image.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://mailtrack.io/trace/link/21b6d7a235c1bce1b64add4d542bbc286aa35313?url=https%3A%2F%2Fgithub.com%2Falan345%2Fnacho%2Fissues%2F221%23issuecomment-434459756&userId=3574407&signature=504fd6a07b7337db>,
> or mute the thread
> <https://mailtrack.io/trace/link/bc5c00ea9e093b34390f5109c50e1cde35679804?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATxcjZZAHBbr9Dh_HgscSBlWRXpoa3Tjks5uqLi9gaJpZM4YCoVt&userId=3574407&signature=efe18b28427abd5a>
> .
>


-- 
Sanjay Goel
Founder, NachoNacho
<https://mailtrack.io/trace/link/c9b20dc47caaca5a9ba8af31db7de857ea39145b?url=https%3A%2F%2Fnachonacho.com%2F&userId=3574407&signature=cda7fcd04b785a86>
sanjay@nachonacho.com
+1 917 497 0779
Linkedin
<https://mailtrack.io/trace/link/b4bc67e99cb09b37f4e2d8c12ede933c9f0d57c7?url=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fsanjaygoel007%2F&userId=3574407&signature=e288c30d9aec9fd6>

**Comment by alan345** [comment]
done
