### ISSUE TITLE
are we set up for google webmaster tools?   I'd like to figure out a way to see if any users arrive at NN.com via google search, what search terms they used...

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#228]

**Comment by alan345** [comment]
![image](https://user-images.githubusercontent.com/15246526/48666875-ec894c80-ea7e-11e8-9988-a026ae936bd1.png)

https://search.google.com/u/3/search-console?resource_id=https%3A%2F%2Fnachonacho.com%2F
![image](https://user-images.githubusercontent.com/15246526/48666877-fad76880-ea7e-11e8-9334-14ab0dd5e3c5.png)
