### ISSUE TITLE
UI for changing sort order of categories

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#230]
at the moment it's hard to change the sort order for categories, since orderByInt and orderByHomeInt
 are only visible after I click into a category....
I need to be able to see these numbers for all the categories on the same page...

Perhaps show those numbers on this page and make them editable directly on this page?  https://nachonacho.com/all

**Comment by alan345** [comment]
Click on this button, 
![image](https://user-images.githubusercontent.com/15246526/48666849-8ac8e280-ea7e-11e8-8dbb-9feeb415336d.png)

you will see boxes to edit all categories
https://github.com/alan345/nacho/commit/2a7dc7f9f72d968dbdc79290bbda5645fd405927
