### ISSUE TITLE
UI for log in/sign up on Product page

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#231]
For non-logged-in-user, if I click on 'Log in to continue', I see this:

![image](https://user-images.githubusercontent.com/20733069/48390147-6f905880-e6b5-11e8-91af-2d337fa46e7a.png)

But if I click on Sign up, I see this:

![image](https://user-images.githubusercontent.com/20733069/48390165-80d96500-e6b5-11e8-83f5-997ab5516276.png)

I should be able to go back to 'Log in' if I clicked on 'Sign up' by mistake, like here: 
![image](https://user-images.githubusercontent.com/20733069/48390193-9cdd0680-e6b5-11e8-8d60-0bdf2c5b7d7b.png)

**Comment by alan345** [comment]
solved
https://github.com/alan345/nacho/commit/2a7dc7f9f72d968dbdc79290bbda5645fd405927
