### ISSUE TITLE
Yelp like redirection UX when user clicks on link to Seller's site on product page

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#235]
Here's an example: https://www.dropbox.com/s/pk5gt99cctugz1c/yelp%20redirection.mov?dl=0

On the redirection page, we can say:

"You are leaving NachoNacho to go to Seller's site.  Feel free to explore the Seller's site.

Don't forget to come back to NachoNacho to subscribe and get further discounts!"

**Comment by alan345** [comment]
done
https://nachonacho.com/product/kapwing
