### ISSUE TITLE
Need test Mode for Sellers/Influencers/Admin

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#268]
I'm using Seller account: sanjay.goel@oximity.com

If I switch to Test Mode, I see 
<img width="938" alt="screen shot 2018-12-18 at 7 04 44 pm" src="https://user-images.githubusercontent.com/20733069/50196401-d974d100-02f7-11e9-8c9d-7b98183ead26.png">

which is the same as I see when in Live Mode.   So I cannot test a product that has not been on-boarded yet...

**Comment by alan345** [comment]
I guess we saw the answer here: 
https://nachonacho.atlassian.net/wiki/spaces/PD/pages/75792385/Website+modes
