### ISSUE TITLE
when there is only 1 PF, don't show title (e.g.: MONTHLY, QUARTERLY, etc.)

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#274]
<img width="1292" alt="screen shot 2018-12-19 at 11 50 02 am" src="https://user-images.githubusercontent.com/20733069/50245702-0375d400-0388-11e9-9793-c09e0345e2db.png">

**Comment by alan345** [comment]
done
![image](https://user-images.githubusercontent.com/15246526/50253099-f1069500-039d-11e9-8396-4e9b20280034.png)
