### ISSUE TITLE
sign up instructions page fine-tuning

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#279]
1) I cannot insert line breaks in buyerOnboardingInstructions:
![image](https://user-images.githubusercontent.com/20733069/50263608-80766d00-03cb-11e9-9934-db3156dcdc67.png)

2) This page should always be available to the Buyer, since he may not take the time to follow all the instructions immediately.  Perhaps the 'Sign up' button can lead to a new page, that is similar page to the Thank you page, with the following changes:
a) Title should be 'Set up your Fitbod account!' instead of 'Thank you for your order!'
b) Remove the copy 'Your order for Fitbod subscription has been received. You will receive a confirmation email shortly.'

In the case of Fitbod, we will not know if/when the Buyer has actually set up the account, so we can just keep the 'Sign up' button always active.  The risk is that the user can set up multiple accounts with the same link!  We can take this risk in the short-term.

**Comment by alan345** [comment]
![image](https://user-images.githubusercontent.com/15246526/50307498-71d09a00-044d-11e9-88d4-f834592e90d7.png)

**Comment by alan345** [comment]
we had a page for calling again the thanks you page. we decided to get rid of it.
Not it is back
![image](https://user-images.githubusercontent.com/15246526/50308131-4484eb80-044f-11e9-9e57-c4a4887e548e.png)
