### ISSUE TITLE
Tags should not be clickable

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#280]
If I click on ON-DEMAND WORKOUT capsule here: 
![image](https://user-images.githubusercontent.com/20733069/50321340-48cbfb80-0485-11e9-9650-cfe601037edf.png)

it brings me here:
![image](https://user-images.githubusercontent.com/20733069/50321330-3e116680-0485-11e9-895e-a8042cef8e45.png)
This page should not be accessible to users, since we don't maintain the design of this page.

**Comment by alan345** [comment]
solved
https://github.com/alan345/nacho/commit/02b163a3fc6241ac9027828247fc1838bb90e291
