### ISSUE TITLE
New account confirmation email

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#3]
For some reason, I am not getting account confirmation email to goel.sanjay@gmail.com.   I tried a couple of days ago.... and again today (I deleted the account and signed up again).

It's working fine for sanjay@sanjaygoel.com and sanjaygoel4@yahoo.com.

**Comment by alan345** [comment]
For testing purpose, I am using this gmail email:     
  userMail: 'emailgooplus@gmail.com',
  passMail: 'in CHAT',


If you go to sent mail, you see that email was sent to goel.sanjay@gmail.com
--


:
![image](https://user-images.githubusercontent.com/15246526/42845769-e322f718-89cb-11e8-9d12-64efc1694214.png)
