### ISSUE TITLE
Make category URL's user friendly

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#35]
Instead of:
http://demo.nachonacho.com/#/category/cjk6fghr0063p0748jq61h6fi

it should be
http://demo.nachonacho.com/#/category/video

**Comment by alan345** [comment]
can it be http://demo.nachonacho.com/#/category/video/cjk6fghr0063p0748jq61h6fi

like amazon: 
https://www.amazon.com/mDesign-Household-Storage-Video-Games/dp/B019NO9HGG/

**Comment by sanjay-goel** [comment]
Better like this: https://www.therealreal.com/watches

If an Admin creates two categories with same name, just add -1 at end
eg:  
http://demo.nachonacho.com/#/category/video
http://demo.nachonacho.com/#/category/video-1

Also, better to remove '#' from the URL if possible
