### ISSUE TITLE
2 decimals for all prices

### ISSUE THREAD

**Issue by alan345** [alan345/nacho#39]

**Comment by alan345** [comment]
![image](https://user-images.githubusercontent.com/15246526/43431815-b332b4b8-9424-11e8-83ba-e523a1d32c9d.png)

**Comment by sanjay-goel** [comment]
Some prices in My Account are still without 2 decimals.

![screen shot 2018-08-01 at 9 40 27 pm](https://user-images.githubusercontent.com/20733069/43562803-a10edf18-95d3-11e8-8471-fb0e7cb9192c.png)
