### ISSUE TITLE
On the Review Order page, if the Buyer has more than 1 credit card in their profile, we should only show the default card.  At the moment, it shows both.   There should be an option to switch it to another card (already in the Buyer's profile), like in Amazon.

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#41]

**Comment by alan345** [comment]
![image](https://user-images.githubusercontent.com/15246526/43487597-f90dd89e-94cb-11e8-8d28-14c9a8bfe932.png)

We need to discuss what I keep, What I hide in checkout page

**Comment by sanjay-goel** [comment]
Ideally, we should have only the default card showing, and a small link that says: 'switch payment method'... then the other cards are shown - maybe by expanding the box, and user can select a different one - as soon as he selects another one, it shrinks the window back to just 1 card

**Comment by sanjay-goel** [comment]
Actually, thinking more about it, user should not be able to change credit cards per order - only for the whole account.   One of our value propositions to user is that they make 1 payment once a month.   If different products are on different credit cards, that won't be possible.  Let's discuss further... I need to leave for now....

**Comment by alan345** [comment]
I am afraid of exceptions of this behavior. what if user has 1 card only. what is card is set as default but not valid anymore..
 This is the same component as 'my account' => 'My payments'

**Comment by alan345** [comment]
I agree with your second comment. 

also, when batch will run every 1st of the month, it will do 1 paiements for all subscriptions with only 1 card (default card)

**Comment by sanjay-goel** [comment]
The payment info in the checkout page serves a very different purpose than in the My Account>My payments page:

* In the checkout page, it should be very short information: Name of credit card, and last 4 digits.  Eg: Mastercard ending in 2890.   We don't need any functionality here regarding credit card.   If the user wants to change it, he will need to go to accounts page himself.  The main idea is to make the checkout as easy and quick as possible.

* In the My Account>My Payments page, we need to allow user to enter more credit cards, delete cards, and change default.

**Comment by sanjay-goel** [comment]
I thought about this further overnight.
When I rent a movie on Apple iTunes, it doesn't show me any payment details.... it is implicit that it will be charged to my account on file.
I think this applies to us as well.  So we can remove the Billing address and Payment card components entirely from the Review Order page.

**Comment by alan345** [comment]
@sanjay-goel sounds good. to summarize checkout: 
1/ page 1: Billing address. If available, skip to page2
2/ page2: Card. If available, skip to page2
3/ page3: Review Order page. made of:
-check email confirmed
-price product + discount
-title porduct
-NO CARD / NO Billing ADDRESS
