### ISSUE TITLE
Give specifications for product & category data

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#48]
* Name of product: Max number of characters

* Short description: Max number of characters

* Category page photo: aspect ratio

Also, limit the number of characters in Admin edit mode for name of product and Short Description

**Comment by alan345** [comment]
1/ for Hero image, I follow the 4 diferents size listed here: https://gist.github.com/gokulkrishh/242e68d1ee94ad05f488
2/ for image categorie, and home page, ratio must be: (2000x1600=>ratio: 2)
3/ for image product LOGO, Min:(600x480=>ratio: 1.25) Ideal:(600x600=>ratio: 1)

**Comment by sanjay-goel** [comment]
Please also give max. no. of chars for Name of Product and Short Description, and limit it in the Edit field.
