### ISSUE TITLE
Footer on My Account page is too high...

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#50]
It makes me scroll even though there is room below the footer.
![screen shot 2018-08-01 at 9 30 03 pm](https://user-images.githubusercontent.com/20733069/43562584-457006ec-95d2-11e8-846f-d326f5b90f3e.png)

**Comment by alan345** [comment]
solved here: https://github.com/alan345/nacho/commit/508cdbb977767f91f04e3e01bac17198ae7932f6
