### ISSUE TITLE
in category page, I suggest to upload 2 images for hero image: Desktop and mobile

### ISSUE THREAD

**Issue by alan345** [alan345/nacho#53]
Ok.... please let me know ideal dimensions for each one.

**Comment by alan345** [comment]
Pro:
 faster to load for mobile, as image might be smaller

cons: 
2 images to load when create categ

@sanjay-goel what do you think?

**Comment by sanjay-goel** [comment]
Let's try that.   Can you let me know the optimal image dimensions for desktop and mobile

**Comment by sanjay-goel** [comment]
Image size:
Home Page: 1280 x500
Mobile: 720 x 300

Title
Subtile: max. characters: 70
