### ISSUE TITLE
On mobile, logged-out-home-page: under hamburger menu, separate Log in and Sign up commands, to be consistent with desktop

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#56]

**Comment by alan345** [comment]
![image](https://user-images.githubusercontent.com/15246526/43688030-3e48b44c-9896-11e8-97cc-ec16e56415a1.png)

**Comment by alan345** [comment]
https://github.com/alan345/nacho/commit/6a12fb0e87bd5e37b369d3cc744897822af1b839
