### ISSUE TITLE
When there is 0 days free trial, don't show it at all.

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#64]

**Comment by alan345** [comment]
done here: https://github.com/alan345/nacho/commit/731355384b5d2e2bd3f6e8bebfa347eacfb141a8

**Comment by sanjay-goel** [comment]
I'm not sure it's working:  http://demo.nachonacho.com/product/aaa
![screen shot 2018-08-13 at 4 43 17 pm](https://user-images.githubusercontent.com/20733069/44064058-16e08c44-9f18-11e8-8089-7fbdaf096c7b.png)
