### ISSUE TITLE
Seller Signup Fields

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#86]
Make First Name, Last Name, email and password the default fields for all Products.  And prefill the first 3 with the Buyer's info that we already have.

All fields that can be turned on/off:
- First name
- Last name
- email
- password
- security question(s)
- username
- mobile number (Select Country (and therefore country code) separately and add number separately)
- country only
- zip code only
- full address (Address Line 1, Address LIne 2, City, State/Province, zip code, Country)
- birth year (YYYY)
- full birthday (MM, DD, YYYY)
- gender (Male/Female/Other or Prefer not to say)

**Comment by alan345** [comment]
@sanjay-goel I suggest to add an open field in product page (with choice, like type of field (string, number), postions, mandatory or not.. ).  with a + button (to add as many fields you wants).

then you can add as many type of fields as you wants. no limitations!

**Comment by sanjay-goel** [comment]
good idea!  we will need to do some design iterations - for example, address will have multiple fields but they should be all grouped together

**Comment by sanjay-goel** [comment]
also, to save me the work of setting up the fields for each product, it would be great if you can set up the default fields for all products

**Comment by alan345** [comment]
As field are going to be generated dynamically, what kind of design are you thinking of? It will not be possible to do some css on top of it. Hence we will be very limitated

**Comment by sanjay-goel** [comment]
Let's do the first iteration as you envision it... we can then fine-tune it afterwards....
