### ISSUE TITLE
Save the Current Seller Signup Page (showing 3 options) so that it can be accessed by admin from My Subscriptions page

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#87]

**Comment by alan345** [comment]
![image](https://user-images.githubusercontent.com/15246526/44630524-cdfa3600-a913-11e8-83f7-c2efb3a6d59e.png)

https://github.com/alan345/nacho/commit/6c774608670f78f752f6e11895d426c0a2557bf3
