### ISSUE TITLE
Password logs for demo site

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#89]
Current passwords:
nacho
sanjay
Calm
ZenMixer

**Comment by sanjay-goel** [comment]
Please add following: 
thomas
zenmixer
sinemia
calm

and remove 
ZenMixer
Calm

**Comment by alan345** [comment]
this.state.pass === 'thomas' ||
          this.state.pass === 'zenmixer' ||
          this.state.pass === 'sinemia' ||
          this.state.pass === 'nacho' ||
          this.state.pass === 'sanjay' ||
          this.state.pass === 'waltermd' || 
          this.state.pass === 'alan'
          || true
