### ISSUE TITLE
Don't allow user to subscribe to same product twice

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#9]
On Home Page and Product Page, say 'Subscribed' instead of 'See Details', and don't show any pricing or discounting.
On Home Page, user can still click on 'Subscribed' to go to product page.  
On Product Page, instead of 'Subscribe', show 'Already Subscribed', and make it un-clickable.

**Comment by alan345** [comment]
done. code: https://github.com/alan345/nacho/commit/aea42c51d123e2f707fbca1ff4225e488f5e474d
