### ISSUE TITLE
Signed up but logged out user scenario

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#91]
If a user:
* is signed up
* has 1 or more subscriptions already
* is logged out

he will see a different price in the review order page before logging in and after logging in.    Need to think about how to address this issue.

**Comment by alan345** [comment]
Do you have an idea in mind? It's normal not to see the same price when you are logged in on not. The system must know who you are to show a discounted price..

**Comment by sanjay-goel** [comment]
<img width="1259" alt="screen shot 2018-09-27 at 2 30 47 pm" src="https://user-images.githubusercontent.com/20733069/46175776-f605ed80-c261-11e8-9ac3-138ab4780450.png">
<img width="1259" alt="screen shot 2018-09-27 at 2 30 43 pm" src="https://user-images.githubusercontent.com/20733069/46175777-f605ed80-c261-11e8-9d69-4efce5a6e1c0.png">

On Product Page:
Next to price, show button: 'Log in to see your price'
Log in box appears

On Checkout Page:
change copy from 'Log in' to 'Log in to see your price'

**Comment by alan345** [comment]
done
![image](https://user-images.githubusercontent.com/15246526/46182143-e34de180-c27e-11e8-9d89-56361670a770.png)

![image](https://user-images.githubusercontent.com/15246526/46182184-15f7da00-c27f-11e8-8952-59cfa2b4ba82.png)
