### ISSUE TITLE
fix gender issues in My Profile

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#94]
<img width="271" alt="screen shot 2018-08-25 at 12 50 18 pm" src="https://user-images.githubusercontent.com/20733069/44622030-96cd4b80-a865-11e8-837f-7123460cf95c.png">

1) When I select gender in dropdown menu, it says 'Male', but in my profile it says 'male'.

2) Once I select a gender, I cannot change it back to 'blank'... there should be a third option which is 'blank'

**Comment by alan345** [comment]
![image](https://user-images.githubusercontent.com/15246526/44630377-372c7a00-a911-11e8-985f-a4fcb03b0c2c.png)

**Comment by alan345** [comment]
https://github.com/alan345/nacho/commit/fb02ace113325b08328f711e68788753e3437fae
