### ISSUE TITLE
Fix UI for drop-down menu under profile photo

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#95]
<img width="168" alt="screen shot 2018-08-25 at 12 53 20 pm" src="https://user-images.githubusercontent.com/20733069/44622057-fb88a600-a865-11e8-9eca-dcf097ce36ac.png">

When user clicks on it, the menu covers most of the photo, so it's hard to make the menu go away.   The menu should open a bit further down, so I can easily click on the photo a second time to make the menu go away

**Comment by alan345** [comment]
![image](https://user-images.githubusercontent.com/15246526/44752512-0fcfdb80-aad0-11e8-94c1-4812d6f725c0.png)
https://github.com/alan345/nacho/commit/4000b304391e7014fbc78369b59ca0099ebe0432
