### ISSUE TITLE
Add cancel button when adding new credit card

### ISSUE THREAD

**Issue by sanjay-goel** [alan345/nacho#97]
<img width="1190" alt="screen shot 2018-08-25 at 11 52 05 pm" src="https://user-images.githubusercontent.com/20733069/44625601-08d37e00-a8c2-11e8-877f-4a9c1550b8b8.png">

Next to the Save button we can add a Cancel button

**Comment by alan345** [comment]
done
![image](https://user-images.githubusercontent.com/15246526/44630420-20d2ee00-a912-11e8-84dd-ef6f3837af9f.png)

https://github.com/alan345/nacho/commit/6c774608670f78f752f6e11895d426c0a2557bf3
